Homework4.exe: main.cpp loans.h loans.cpp patrons.h patrons.cpp dvd.h dvd.cpp audio.h audio.cpp loan.h loan.cpp patron.h patron.cpp book.h book.cpp item.h item.cpp items.h items.cpp
	g++ book.cpp audio.cpp dvd.cpp item.cpp items.cpp patron.cpp patrons.cpp loan.cpp loans.cpp main.cpp -o Homework3.exe

clean:
	rm *.o output
