Homework3.exe: main.cpp loans.h loans.cpp patrons.h patrons.cpp books.h books.cpp loan.h loan.cpp patron.h patron.cpp book.h book.cpp
	g++ book.cpp books.cpp patron.cpp patrons.cpp loan.cpp loans.cpp main.cpp -o Homework3.exe

clean:
	rm *.o output
